#### Tensor 이해 - 생성
- Tensor란?
    * pytorch에서 데이터를 저장하는 객체
    * 모델에 입력/출력 데이터 형태

In [1]:
## 모듈 로딩
import torch

- Tensor 생성 [2] torch.rand()

In [2]:
# 0 <= ~< 1 범위의 임의의 숫자 1개 추출 => rand(*size)
# rand(*size) : 가변인자 ==> 몇 차원일지 알 수 없음!!
torch.manual_seed(1)

dataTS1 = torch.rand(1)         # 1D Vector
dataTS2 = torch.rand(2,3)       # 2D Matrix
dataTS3 = torch.rand(1,2,3)     # 3D Tensor

In [3]:
print(dataTS1, dataTS2, dataTS3, sep='\n')

tensor([0.7576])
tensor([[0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971]])
tensor([[[0.7544, 0.5695, 0.4388],
         [0.6387, 0.5247, 0.6826]]])


- Tensor 생성 [3] torch.randn()

In [4]:
dataTS1 = torch.randn(1)         # 1D Vector
dataTS2 = torch.randn(2,3)       # 2D Matrix
dataTS3 = torch.randn(1,2,3)     # 3D Tensor

In [5]:
print(dataTS1, dataTS2, dataTS3, sep='\n')

tensor([-1.3328])
tensor([[ 0.5161,  0.7455, -0.0751],
        [-0.6919, -0.4043,  0.2222]])
tensor([[[ 0.5773, -1.7637,  0.2264],
         [-0.2355,  0.3019, -0.2770]]])


- Tensor 생성 [4] torch.randint()

In [6]:
# 1D Vector
torch.randint(1,46,(4, 6))

tensor([[15,  6, 24, 19, 16, 19],
        [25, 12,  5, 40, 31, 14],
        [16, 37, 44, 42, 45, 13],
        [ 4, 32, 35, 40, 24,  4]])