# 넘파이 특화 함수 알아보기 (Chapter 11)

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

### 일반함수와 람다함수 사용하기

- 유니버셜 함수
    - 유니버설 함수 클래스인 ufunc 클래스를 확인해 봅니다. 덧셈을 처리하는 함수 add를
    만든 클래스를 type으로 확인하면 유니버설 함수 클래스라는 것을 알 수 있습니다. 
    또한 여러 개의 메소드를 가지고 있습니다. 

In [3]:
np.ufunc

numpy.ufunc

In [4]:
type(np.ufunc)

type

In [5]:
for i in dir(np.ufunc):
    if not i.startswith('_'):
        print(i)

accumulate
at
identity
nargs
nin
nout
ntypes
outer
reduce
reduceat
resolve_dtypes
signature
types


- 유니버셜 함수 : 내부 메소드 처리
    - 유니버셜 함수 add내의 reduce, reduceat 메소드로 배열의 원소를 계산합니다. 

In [6]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import functools as ft

In [8]:
ft.reduce(np.add, a)

45

In [9]:
np.add.reduce(a)

45

In [10]:
a.sum()

45

In [11]:
np.add.reduceat(a,[0,4])

array([ 6, 39])

In [12]:
np.add.reduce(a[:4])

6

In [13]:
np.add.reduce(a[4:])

39

- 사용자 유니버셜 함수 정의하기
    - 넘파이 모듈에서 제공되는 함수들만을 사용해서 개발도 가능하지만 사용자가 직접
    정의한 함수를 유니버설 함수로 등록해서 사용할 수 있습니다. 

In [14]:
np.frompyfunc

<function numpy.frompyfunc>

In [15]:
type(np.frompyfunc)

builtin_function_or_method

In [16]:
np.frompyfunc.__class__

builtin_function_or_method

In [17]:
import operator as op

In [18]:
def add(x,y):
    return op.add(x,y)

In [19]:
type(add)

function

In [20]:
a = np.arange(3)
b = np.arange(4,7)
c = add(a,b)
c

array([4, 6, 8])

In [21]:
add_ = np.frompyfunc(add,2,1)

In [22]:
type(add_)

numpy.ufunc

In [23]:
d = add_(a,b)
d

array([4, 6, 8], dtype=object)

- vectorize 함수 사용하기
    - 사용자 함수를 정의하고 새로운 인스턴스를 만들어서 다차원 배열을 바로 계산할 수
    있도록 만들어줍니다.

In [24]:
np.vectorize

numpy.vectorize

In [25]:
type(np.vectorize)

type

In [26]:
np.vectorize.__class__

type

In [27]:
def mul(x,y):
    return op.mul(x,y)

In [28]:
type(mul)

function

In [29]:
mul_ = np.vectorize(mul, otypes=[np.int32])

In [30]:
type(mul_)

numpy.vectorize

In [31]:
a = np.arange(3)
b = np.arange(4,7)
c = mul(a,b)
c

array([ 0,  5, 12])

In [32]:
d = mul_(a,b)
d

array([ 0,  5, 12])

- 함수를 전달 받아서 배열 생성하기
    - 특정 함수를 사용해서 배열의 좌표에 맞춰 형상에 맞춰 새로운 배열을 만들 수 있습
    니다. 

In [33]:
np.fromfunction

<function numpy.fromfunction(function, shape, *, dtype=<class 'float'>, like=None, **kwargs)>

In [34]:
type(np.fromfunction)

function

In [35]:
a = np.fromfunction(lambda i,j : i == j, (3,3), dtype=np.int32)
a

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [36]:
b = np.fromfunction(lambda i,j : i+j, (3,3), dtype=np.int32)
b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### 파일 처리

- 파일 처리
    - 다차원 배열을 파일에 저장해서 일반적인 데이터를 저장합니다. 다시 읽어오면
    다차원 배열로 변환해서 저장합니다.

In [37]:
n = np.random.randn(3,5)
n

array([[-0.70493646,  1.09263595, -1.16327735, -1.69137948, -0.11867659],
       [-0.62145932,  0.38530685, -0.28230446, -0.99998439,  1.36615572],
       [-0.58762291,  0.85650986,  0.42890504, -0.08791538, -0.15112795]])

In [38]:
n.tofile('n.npy')

In [39]:
m = np.fromfile('n.npy')
m

array([-0.70493646,  1.09263595, -1.16327735, -1.69137948, -0.11867659,
       -0.62145932,  0.38530685, -0.28230446, -0.99998439,  1.36615572,
       -0.58762291,  0.85650986,  0.42890504, -0.08791538, -0.15112795])

In [40]:
np.save('m.npy',m)

In [41]:
o = np.load('m.npy')
o

array([-0.70493646,  1.09263595, -1.16327735, -1.69137948, -0.11867659,
       -0.62145932,  0.38530685, -0.28230446, -0.99998439,  1.36615572,
       -0.58762291,  0.85650986,  0.42890504, -0.08791538, -0.15112795])

- 텍스트 파일 처리
    - 텍스트 파일로 저장하기 위해 savetxt 함수에 파일 이름과 배열을 전달합니다
    - %load 명령어와 loadtxt 함수로 파일을 읽어봅니다

In [42]:
a = np.random.randn(3,3)
a

array([[-0.28111037,  0.41010273,  0.21134091],
       [ 0.90249863, -0.0960575 ,  0.65129064],
       [-0.66038651, -1.15586151, -1.0149903 ]])

In [43]:
np.savetxt('data.txt',a)

In [44]:
# %load data.txt
-2.811103730679128665e-01 4.101027326297668196e-01 2.113409063839132296e-01
9.024986270536339283e-01 -9.605749916171980873e-02 6.512906361177838166e-01
-6.603865129778109244e-01 -1.155861509125136743e+00 -1.014990299384677774e+00


In [45]:
b = np.loadtxt('data.txt')
b

array([[-0.28111037,  0.41010273,  0.21134091],
       [ 0.90249863, -0.0960575 ,  0.65129064],
       [-0.66038651, -1.15586151, -1.0149903 ]])

- CSV 파일 처리
    - 파일을 genfromtxt 함수로 읽어옵니다. 다차원 배열로 변환해서 처리합니다.

In [48]:
# %%writefile data.dat

In [49]:
# data = np.genfromtxt('fifle.dat')
# data

In [50]:
# np.savetxt('file.csv',data)

In [51]:
# a = np.loadtxt('file.csv')
# a

- 직렬화 처리
    - 파이썬에서 제공되는 확장자는 파이썬 객체를 그대로 저장해서 처리할 수 있습
    니다. npz확장자를 사용하면 다차원 배열을 직렬화 처리를 하고 저장합니다

In [52]:
x = np.random.randn(3,5)
x

array([[-1.71688026, -0.55096301,  0.03985326,  0.21605418,  0.02976896],
       [ 0.75843512,  0.375494  ,  1.3770617 , -1.23839079, -0.1340178 ],
       [-0.46641275, -0.65109077,  0.17603459, -0.20257077, -0.67124537]])

In [53]:
np.savez('x',x)

In [54]:
y = np.load('x.npz')

In [55]:
y['arr_0']

array([[-1.71688026, -0.55096301,  0.03985326,  0.21605418,  0.02976896],
       [ 0.75843512,  0.375494  ,  1.3770617 , -1.23839079, -0.1340178 ],
       [-0.46641275, -0.65109077,  0.17603459, -0.20257077, -0.67124537]])