# 방정식, 미적분, 합성곱 알아보기 (Chapter 10)

### 방정식 알아보기

- 방정식 처리 알아보기
    - 다항식은 poly1d 클래스 생성자에 계수를 가진 1차원 배열을 넣어서 다항식 객체를
    만듭니다. 만들어진 객체는 수식으로 표현도 가능하고 이 방식의 근도 구할 수 있습
    니다. 

In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
ef = np.array([1,-2,1])

In [5]:
p = np.poly1d(ef)
p

poly1d([ 1, -2,  1])

In [6]:
print(p)

   2
1 x - 2 x + 1


In [7]:
type(p)

numpy.poly1d

In [8]:
p.variable

'x'

In [9]:
p.order

2

In [10]:
p.coef

array([ 1, -2,  1])

In [11]:
p.coefficients

array([ 1, -2,  1])

In [12]:
p.coeffs

array([ 1, -2,  1])

In [13]:
p.roots

array([1.+6.68896751e-09j, 1.-6.68896751e-09j])

In [14]:
p(0)

1

In [15]:
np.polyval([1,-2,1],0)

1

In [16]:
np.polyval([1,-2,1],5)

16

- 연립방정식 이해하기
    - 여러 개의 방정식을 가지고 해를 구하는 것을 연립 방정식을 행렬로 변환해서 계산을 할 수 있습니다. 다차원 배열을 사용해서 연립 방적식의 해를 구해봅니다. 

In [17]:
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
x = np.linalg.solve(a,b)
x

array([2., 3.])

In [18]:
np.allclose(np.dot(a,x),b)

True

In [19]:
A = np.array([[1,0,0],[1,1,1],[6,7,0]])
b = np.array([0,24,0])

In [20]:
A_1 = np.linalg.inv(A)

In [21]:
x = np.dot(A_1, b)
x

array([ 0.,  0., 24.])

In [22]:
np.allclose(np.dot(A_1, b), x)

True

In [23]:
np.linalg.solve(A, b)

array([ 0., -0., 24.])

In [24]:
np.allclose(np.dot(A_1, b), x)

True

- lstsq 함수로 연립 방정식 풀기
    - 최소자승 문제(least square problem)의 답과 같은 결과입니다. 이 함수는 세 가지 결
    과를 추가해서 반환합니다. 잔차제곱합(residual sum of squares), 랭크, 그리고 특이값
    (singular value)을 반환합니다.

In [25]:
np.linalg.matrix_rank(A)

3

In [26]:
x, resid, rank, singular = np.linalg.lstsq(A, b, rcond=-1)

In [27]:
x

array([ 3.05504346e-15, -2.56636673e-15,  2.40000000e+01])

In [28]:
resid

array([], dtype=float64)

In [29]:
rank

3

In [30]:
singular

array([9.3509151 , 1.        , 0.74858984])

In [31]:
np.allclose(np.dot(A, x), b)

True

### 차분, 미분과 적분

- diff 함수 알아보기
    - 하나의 배열에 내의 원소들 간의 차를 구한 결과를 차분 함수인 diff로 처리합니다.

In [32]:
x = np.array([1, 2, 4, 7, 10])
x

array([ 1,  2,  4,  7, 10])

In [33]:
np.diff(x)

array([1, 2, 3, 3])

In [34]:
np.diff(x, n=2)

array([1, 1, 0])

In [35]:
c = np.diff(x)

In [36]:
np.diff(c)

array([1, 1, 0])

- diff 함수로 미분하기
    - 차분 함수 diff로를 사용해서 미분을 구합니다. 

In [37]:
x = np.array([1,2,3,4,5,6])
dx = np.diff(x)
dx

array([1, 1, 1, 1, 1])

In [38]:
y = np.array([2,4,6,8,10,12])
dy = np.diff(y)
dy

array([2, 2, 2, 2, 2])

In [40]:
dydx = np.zeros(y.shape,np.float64)

In [41]:
dydx[:-1] = dy/dx

In [42]:
dydx

array([2., 2., 2., 2., 2., 0.])

In [43]:
dydx[-1] = (y[-1] - y[-2]) / (x[-1] - x[-2])

In [44]:
dydx

array([2., 2., 2., 2., 2., 2.])

In [45]:
np.gradient(y)

array([2., 2., 2., 2., 2., 2.])

- 다항식으로 미분하기
    - 다항식 객체를 미분할 때는 polyder 함수를 사용합니다. 다항식으로 반환한 결과가 2개의 원소를 가진 다항식의 객체라는 것을 볼 수 있습니다.

In [50]:
a = np.array([1,-2,1])
p = np.poly1d(a)

In [51]:
print(p)

   2
1 x - 2 x + 1


In [52]:
d = np.polyder(p)
d

poly1d([ 2, -2])

In [53]:
d(10)

18

- 중앙 차분으로 미분 구하기
    - 다항식 객체를 미분할 때는 polyder 함수를 사용합니다. 다항식으로 반환한 결과가 2개의 원소를 가진 다항식의 객체라는 것을 볼 수 있습니다.


In [54]:
x = 10

In [55]:
def f(x):
    return x**2

In [56]:
def numerical_differentiation(f,x): # 수치미분
    delta_x = 1e-7
    return (f(x+delta_x)-f(x-delta_x) / (delta_x*2)) # 중앙 차분

In [57]:
nd = numerical_differentiation(f, x)
nd

-499999889.9999981

- Gradient로 미분
    - 다차원 배열에 대한 미분은 gradint 함수로 처리합니다. 두번째 인자가 2일 경우는 중
앙차분으로 미분을 계산합니다. 

In [58]:
x = np.linspace(0,10)
x

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [59]:
dydx = np.gradient(y)
dydx

array([2., 2., 2., 2., 2., 2.])

In [60]:
np.gradient(y,2)

array([1., 1., 1., 1., 1., 1.])

- 적분 알아보기
    - 적분하기 위해서는 trapz 함수의 인자로 y2와 x2를 전달해서 적분을 구합니다. 
    - quad 내에 인자로 전달해서 0부터 4까지의 적분을 계산합니다. 적분한 값과 오차의
    값을 반환하는 것을 볼 수 있습니다. 

In [61]:
x2 = np.arange(5)
x2

array([0, 1, 2, 3, 4])

In [62]:
y2 = x2**2

In [63]:
np.trapz(y2, x=x2)

22.0

In [64]:
from scipy.integrate import quad

In [65]:
x2 = lambda x:x**2
quad(x2, 0, 4)

(21.333333333333336, 2.368475785867001e-13)

### 합성곱 및 필터링 알아보기

- 1D 합성곱 함수 알아보기
    - 합성곱 함수 convolve에 첫 번째 인자는 입력 데이터, 두 번째 인자는 필터, 세 번째 인
    자인 mode은 합성곱 내부의 원소들이 연산하는 횟수를 지정합니다

In [66]:
a = np.array([0, 1, 2, 3, 4, 5, 6])
v = np.array([0.2, 0.7])

In [67]:
same = np.convolve(a,v,mode='same')
same.shape

(7,)

In [68]:
same

array([0. , 0.2, 1.1, 2. , 2.9, 3.8, 4.7])

In [69]:
full = np.convolve(a,v,mode='full')
full

array([0. , 0.2, 1.1, 2. , 2.9, 3.8, 4.7, 4.2])

In [70]:
full.shape

(8,)

- 2D 합성곰 함수 알아보기
    - 2차원 합성곱 연산의 함수는 scipy.sigmal 모듈에 있어 모듈을 import 합니다. 두 개의
    2차원 배열을 인자로 전달해서 합성곱 함수는 convolve2d를 실행합니다

In [71]:
A = [[5, 4, 5, 4],
     [3, 2, 3, 2],
     [5, 4, 5, 4],
     [3, 2, 3, 2]]

A = np.array(A)

In [72]:
k = np.array([0.707, 0.707])

In [73]:
from scipy import signal

In [76]:
# grad = signal.convolve2d(A, k_, boundary='fill', mode='full')
# grad.shape

In [75]:
# grad

- 필터링 알아보기
    - 2다차원 배열을 필터를 기준으로 필터링(fitering)을 통해 같은 형상의 배열을 만듭니
    다. 

In [77]:
B = [[3, 4, 5, 2, 3],
     [3, 5, 1, 2, 7],
     [2, 2, 5, 6, 7]]
B = np.array(B)

In [79]:
from scipy.ndimage import maximum_filter, minimum_filter

In [80]:
maximum_filter(B, size=(2,2))

array([[3, 4, 5, 5, 3],
       [3, 5, 5, 5, 7],
       [3, 5, 5, 6, 7]])

In [81]:
maximum_filter(B, footprint=np.ones((3,3)))

array([[5, 5, 5, 7, 7],
       [5, 5, 6, 7, 7],
       [5, 5, 6, 7, 7]])

In [82]:
minimum_filter(B, size=(2,2))

array([[3, 3, 4, 2, 2],
       [3, 3, 1, 1, 2],
       [2, 2, 1, 1, 2]])

In [83]:
minimum_filter(B, footprint=np.ones((3,3)))

array([[3, 1, 1, 1, 2],
       [2, 1, 1, 1, 2],
       [2, 1, 1, 1, 2]])

- 풀링 알아보기
    - 2다차원 배열 풀링(pooling)을 통해 더 작은 배열을 만드는 방법을 알아본다.
    - 열과 행의 차원을 증가시켜서 최댓값으로 풀링을 처리하면 반환되는 결과가 행이나
    열이 줄어듭니다. 

In [84]:
import skimage.measure

In [86]:
sk = skimage.measure.block_reduce(B, (1,1), np.max)
sk

array([[3, 4, 5, 2, 3],
       [3, 5, 1, 2, 7],
       [2, 2, 5, 6, 7]])

In [87]:
sk = skimage.measure.block_reduce(B, (1,2), np.max)
sk

array([[4, 5, 3],
       [5, 2, 7],
       [2, 6, 7]])

In [88]:
sk = skimage.measure.block_reduce(B, (2,1), np.max)
sk

array([[3, 5, 5, 2, 7],
       [2, 2, 5, 6, 7]])