# 다차원 배열의 구조 변경하기 (Chapter 5)

### 내부 조작 함수

In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

- 정렬함수 : sort
    - 다차원 배열도 내부의 원소를 기준으로 처리를 할 때는 순서대로 정렬을 해서 사용할 수 있습니다

In [4]:
a = np.linspace(1,6,6, dtype=np.int32)
a

array([1, 2, 3, 4, 5, 6])

In [5]:
np.random.shuffle(a)
a

array([2, 4, 3, 1, 6, 5])

In [6]:
b = np.sort(a)
b

array([1, 2, 3, 4, 5, 6])

In [8]:
a.sort()
a

array([1, 2, 3, 4, 5, 6])

- 정렬 함수: argsort
    - 값을 정렬을 하지 않고 인덱스 정렬은 argsort 함수를 사용합니다. 기존 원본 배열의 인덱스를 가지고 정렬한 배열을 반환합니다. 

In [9]:
bb = np.linspace(1,6,6, dtype=np.int32)
bb

array([1, 2, 3, 4, 5, 6])

In [10]:
np.random.shuffle(bb)
bb

array([5, 4, 6, 1, 2, 3])

In [11]:
c = np.argsort(bb)
c

array([3, 4, 5, 1, 0, 2], dtype=int64)

In [12]:
bb[c[0]]

1

In [13]:
bb[c[1]]

2

- 배열 클래스 변경
    - 넘파이 모듈은 다차원 배열인 ndarray와 행렬을 처리하는 matrix 클래스가 있습니다. 이들은 서로 자료형을 교환할 수 있습니다.


In [14]:
m = np.matrix([1,2,3,4])
m

matrix([[1, 2, 3, 4]])

In [15]:
type(m)

numpy.matrix

In [16]:
a = np.asarray(m)
a

array([[1, 2, 3, 4]])

In [17]:
type(a)

numpy.ndarray

In [18]:
m1 = np.asmatrix(a)
m1

matrix([[1, 2, 3, 4]])

- 배열의 값 변경
    - 다차원 배열을 ones 함수로 만들면 모든 원소의 값이 1입니다. 모든 원소를 다른 값으로 변경하려면 fill 메소드를 사용해서 변경합니다. 또한 full 함수는 새로 만드는 배열의 모든 값을 동일하게 처리합니다.

In [19]:
o = np.ones(10)
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
o.fill(100)
o

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])

In [21]:
a = np.full(o.shape, 99.)
a

array([99., 99., 99., 99., 99., 99., 99., 99., 99., 99.])

- 위치변경 및 이동
    - 배열의 좌우, 상하의 위치 및 각도에 따라 이동을 시킬 수 있습니다.

In [22]:
array = np.arange(4).reshape((2,2))
array

array([[0, 1],
       [2, 3]])

In [23]:
np.fliplr(array)

array([[1, 0],
       [3, 2]])

In [24]:
np.flipud(array)

array([[2, 3],
       [0, 1]])

In [26]:
m = np.array([[1,2],[3,4]], int)
m

array([[1, 2],
       [3, 4]])

In [27]:
np.rot90(m)

array([[2, 4],
       [1, 3]])

In [28]:
np.rot90(m,2)

array([[4, 3],
       [2, 1]])

In [29]:
np.rot90(m,3)

array([[3, 1],
       [4, 2]])

In [30]:
np.rot90(m,4)

array([[1, 2],
       [3, 4]])

- 배열 내의 원소 점검하기
    - 원소의 값에 대한 체크를 할 수 있습니다. 또한 무한대나 nan도 점검할 수 있습니다.

In [31]:
m = np.random.randn(3,5)
m

array([[ 0.42482517,  0.25880207,  0.98633812,  0.91082639, -0.14280394],
       [ 0.54517376,  1.35897189,  0.55812423,  0.96252104, -0.55152933],
       [-0.32566321, -0.45281947, -0.07807212, -0.60064695, -1.73649891]])

In [32]:
np.isreal(m)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [33]:
np.isinf(m)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [34]:
np.isnan(m)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

### 배열의 padding 처리

- 패딩
    - 기존 배열 밖에 다른 원소를 더 붙여서 배열을 확장하는 방식입니다.

In [35]:
x = np.arange(1,5).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [36]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
z[:2, :2] = x
z

array([[1., 2., 0.],
       [3., 4., 0.],
       [0., 0., 0.]])

- 패딩 함수 1
    - 함수 pad를 가지고 배열에 패딩을 처리합니다. 상수값으로 패딩을 할 때는 constant 문자열을 인자로 전달합니다

In [38]:
np.pad(x,0,'constant')

array([[1, 2],
       [3, 4]])

In [39]:
np.pad(x, (0,1), 'constant')

array([[1, 2, 0],
       [3, 4, 0],
       [0, 0, 0]])

In [40]:
np.pad(x,(1,0),'constant')

array([[0, 0, 0],
       [0, 1, 2],
       [0, 3, 4]])

In [41]:
np.pad(x,(1,1),'constant')

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

In [42]:
np.pad(x,(3,3),'constant')

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 0, 0, 0],
       [0, 0, 0, 3, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

- 패딩 함수 2
    - 기존 배열의 값으로 패딩이 필요하면 edge 문자열을 인자로 전달합니다.

In [43]:
x = np.arange(1,5).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [44]:
np.pad(x,(0,1),'edge')

array([[1, 2, 2],
       [3, 4, 4],
       [3, 4, 4]])

In [45]:
np.pad(x,(1,0),'edge')

array([[1, 1, 2],
       [1, 1, 2],
       [3, 3, 4]])

In [46]:
np.pad(x,(1,1),'edge')

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [3, 3, 4, 4]])

In [47]:
np.pad(x,(3,3),'edge')

array([[1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4]])

- 패딩 함수 3
    - 패딩되는 값을 최대값, 최소값, 평균, 중앙값 등으로 지정할 수 있습니다.

In [49]:
np.pad(x,(3,3),'maximum')

array([[4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4]])

In [50]:
np.pad(x,(3,3),'minimum')

array([[1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [3, 3, 3, 3, 4, 3, 3, 3],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1]])

In [51]:
np.pad(x,(1,1),'mean')

array([[2, 2, 3, 2],
       [2, 1, 2, 2],
       [4, 3, 4, 4],
       [2, 2, 3, 2]])

In [52]:
np.pad(x,(3,3),'mean')

array([[2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2]])

In [53]:
np.pad(x,(3,3),'median')

array([[2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2]])