# 다차원 배열의 연산 (Chapter 4)

### 산술 연산

In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

- 벡터 덧셈
    - 동일한 원소를 가진 1차원 배열간의 덧셈. 벡터간의 덧셈은 새로운 벡터를 만듭
    니다. 
    - 1차원 배열의 원소 별(element-wide) 덧셈 연산합니다.

In [4]:
d = np.array([3,4])
e = np.array([5,6])

In [5]:
d+e

array([ 8, 10])

In [6]:
np.add(d,e)

array([ 8, 10])

In [7]:
f = np.array([1,2,3])

In [8]:
try:
    f + e
except Exception as ex:
    print(ex)

operands could not be broadcast together with shapes (3,) (2,) 


- 벡터 뺄셈
    - 벡터 간의 뺄셈도 덧셈과 동일하게 평행사변형을 만듭니다. 대신 반대 방향이라
    서 반대 방향의 평행사변형이 그려집니다.
    - 1차원 배열의 원소별 뺄셈처리로 계산합니다.

In [9]:
d = np.array([3,4])
e = np.array([5,6])

In [10]:
d-e

array([-2, -2])

In [11]:
np.subtract(d,e)

array([-2, -2])

In [12]:
d+(-e)

array([-2, -2])

In [13]:
np.add(d, np.negative(e))

array([-2, -2])

- 스칼라 곱셈
    - 특정 벡터가 있을 때 이 벡터를 특정 상수만큼 크기를 확장할 수 있습니다. 이를
스칼라 배라고 합니다. 벡터에 상수를 곱한 결과입니다.


In [14]:
d = np.array([2,3])
d

array([2, 3])

In [15]:
3 * d

array([6, 9])

In [16]:
np.array([3,3]) * d

array([6, 9])

In [17]:
np.multiply(3,d)

array([6, 9])

In [18]:
np.multiply(np.array([3,3]),d)

array([6, 9])

### 브로드캐스팅 이해하기

- 브로드캐스팅
    - 차원이 다른 배열간의 계산을 할 때는 먼저 원소별 계산을 위해 동일한 shape을
구성합니다. 이를 브로드캐스팅입니다.


In [19]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [21]:
z = np.broadcast(x,y)
z

In [22]:
type(z)

numpy.broadcast

In [23]:
z.shape, z.ndim

((2, 5), 2)

In [24]:
for i in z:
    print(i)

(0, 0)
(1, 1)
(2, 2)
(3, 3)
(4, 4)
(5, 0)
(6, 1)
(7, 2)
(8, 3)
(9, 4)


In [25]:
x + y

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

- 브로드캐스팅 처리 규칙
    - 차원이 다른 배열에 대한 연산을 할 때 브로드캐스팅 처리 방법입니다. 

In [26]:
x2 = np.ones((2,3))
x2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
x1 = np.ones(3)
x1

array([1., 1., 1.])

In [28]:
x1.shape, x2.shape

((3,), (2, 3))

In [29]:
x1.shape[0] == x2.shape[1]

True

In [30]:
x1 = x1[np.newaxis,]

In [31]:
x1.shape

(1, 3)

In [32]:
x1 = np.vstack((x1[0],x1[0]))
x1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
x1.shape == x2.shape

True

In [34]:
x1 + x2

array([[2., 2., 2.],
       [2., 2., 2.]])

- 행벡터와 열벡터 브로드캐스팅 확장
    - 행벡터와 열벡터의 연산은 동일한 shape를 구성한 후에 원소별로 계산을 합니다. 

In [35]:
x = np.arange(1,4)
x

array([1, 2, 3])

In [36]:
x1 = x.reshape(1,3)
x1

array([[1, 2, 3]])

In [37]:
x2 = x[np.newaxis,]
x2

array([[1, 2, 3]])

In [38]:
y = np.arange(1,4)
y

array([1, 2, 3])

In [39]:
y1 = y.reshape(3,1)
y1

array([[1],
       [2],
       [3]])

In [40]:
y2 = y[:,np.newaxis]
y2

array([[1],
       [2],
       [3]])

In [41]:
np.broadcast_arrays(x1,y1)

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])]

In [42]:
x1 + y1

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

### 행렬의 연산

- 벡터의 내적
    - 벡터의 내적은 두 벡터의 크기와 내각의 곱, 또는 두 벡터의 원소별 곱셈 후에 더해서
    구할 수 있습니다. 
    - 보통 벡터 내적은 두 벡터가 수직인지 확인할 때 많이 사용 됩니다.


In [43]:
a = np.array([3,4])
b = np.array([5,6])

In [44]:
a @ b

39

In [45]:
np.dot(a,b)

39

In [46]:
np.inner(a,b)

39

- 벡터의 외적
    - 두 벡터의 외적은 두 벡터를 평면으로 인식한 후에 두 벡터의 만나는 점의 수직인 벡
터를 구하는 것입니다

In [47]:
a = np.array([1,4])
b = np.array([3,6])

In [48]:
np.cross(a,b)

array(-6)

In [49]:
c = np.array([1,4,3])
d = np.array([3,4,5])

In [50]:
np.cross(c,d)

array([ 8,  4, -8])

- 행렬 dot product
    - 닷 프로덕트(dot product)는 A 행렬의 행과 B행렬의 연간의 원소를 곱해서 더한 값을
새로운 행렬의 A행렬의 0번 축의 위치와 B행렬의 1번 축의 위치에 해당하는 원소가 됩니다. 
    - 2개의 2행 2열의 배열을 만들고 dot 함수, dot 메소드, @ 연산자로 닷연산을 실행합니다.

In [51]:
a = np.array([[3,4],[5,6]])
a

array([[3, 4],
       [5, 6]])

In [52]:
b = np.array([[5,6],[6,7]])
b

array([[5, 6],
       [6, 7]])

In [53]:
np.dot(a,b)

array([[39, 46],
       [61, 72]])

In [54]:
a.dot(b)

array([[39, 46],
       [61, 72]])

In [55]:
a@b

array([[39, 46],
       [61, 72]])

- 행렬 dot product : 행렬분해이용
    - 두번째 행렬을 열벡터로 분해한 후에 dot product 계산한 결과도 알아봅니다. 

In [56]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [57]:
np.dot(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [58]:
# 열벡터로 변환
c = b[:,0]
d = b[:,1]
e = b[:,2]

In [59]:
c = c[:,np.newaxis]
d = d[:,np.newaxis]
e = e[:,np.newaxis]

In [60]:
# dot product 연산
f = a @ c
g = a @ d
h = a @ e

In [61]:
# 하나로 통합
i = np.concatenate([f,g,h],axis=1)
i

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### 행렬식, 역행력 처리하기

- 행렬식
    - 행렬식(determinant)은 정사각행렬일 때 이 원소들을 대응해서 값을 구하는 방식입니다. 정사
    각행렬이 아닌 경우에는 행렬식을 계산할 수 없습니다. 행렬식으로 계산하면 벡터와 행렬 간
    의 닷연산을 통해 선형 변환한 결과의 부피를 구할 수 있습니다. 또한 행렬식을 사용해서 연립
    방정식의 해를 구할 때도 사용합니다.
    - 행렬이 차원이 커질 경우 행렬식을 구할 때는 소행렬식을 사용해서 행렬식을 구할 수 있습니
    다. 3행 3열의 배열을 소행렬식으로 계산하기 위해 첫 번째 행을 제외하고 나머지 두 개의 행을
    2행 2열로 만들어서 소행렬식을 구하고 첫 번째 행의 값을 곱한 후에 부호를 조정하면 행렬식
    계산과 같습니다

In [63]:
a = np.array([[3,1],[2,2]])

In [64]:
np.linalg.det(a)

4.000000000000001

In [65]:
np.allclose(4.0,np.linalg.det(a))

True

In [66]:
b = np.array([[3,1,3],[2,2,3],[1,1,1]])
b

array([[3, 1, 3],
       [2, 2, 3],
       [1, 1, 1]])

In [67]:
3*np.linalg.det(b[1:, 1:])

-3.0

In [68]:
np.linalg.det(b[1:, ::2])

-1.0

In [69]:
3 * np.linalg.det(b[1:, :2])

0.0

In [70]:
np.linalg.det(b)

-2.0

In [71]:
-3 + 1 + 0

-2

- 역행렬(Inverse Matrix)
    - 역행렬을 구할 때 행렬식의 결괏값으로 나누는 것은 매우 중요합니다. 행렬식이 0이 나오면 수
학적인 계산이 불가해서 역행렬을 계산하지 못합니다.

In [72]:
a = np.array([[3,2],[6,4]])

In [73]:
np.linalg.det(a)

0.0

In [74]:
b = np.array([[1,2,3],[4,5,6],[3,2,4]])

In [75]:
np.linalg.det(b)

-9.000000000000002

In [76]:
bi = np.linalg.inv(b)

In [77]:
bb = np.dot(b, bi)

In [78]:
np.allclose(np.eye(3),bb)

True

- 역행렬의 교환법칙
    - 역행렬의 행렬곱 연산은 반대로 계산해도 동일한 단위행렬이 나옵니다. 단위행렬은 보통 대문
자 I로 사용하지만 대문자 E로도 표기하는 경우도 있습니다. 

In [79]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [80]:
ai = np.linalg.inv(a)
ai

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [81]:
x = np.dot(a, ai)
x

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [82]:
np.allclose(np.eye(2), x)

True

In [83]:
y = np.dot(ai, a)
y

array([[ 1.00000000e+00,  4.44089210e-16],
       [-5.55111512e-17,  1.00000000e+00]])

In [84]:
np.allclose(np.eye(2), y)

True

In [85]:
np.allclose(x, y)

True

- 역행렬의 분배처리
    - 두 행렬 A, B의 행렬곱을 하면 하나의 행렬이 만들어집니다. 이를 -1을 위 첨자로 사용해서 역행
렬을 표시할 수 있습니다. 이 산식을 전개하면 두 행렬의 위치가 변경되고 각 행렬마다 위 첨자
를 사용해서 역행렬을 표시합니다. 

In [86]:
a = np.array([[1,2],[3,4]])

In [87]:
np.linalg.det(a)

-2.0000000000000004

In [89]:
b = np.array([[3,4],[1,2]])

In [90]:
np.linalg.det(b)

2.0000000000000004

In [91]:
ai = np.linalg.inv(a)
bi = np.linalg.inv(b)

In [92]:
ab = np.linalg.inv(np.dot(a, b))

In [93]:
ba = np.dot(bi, ai)

In [94]:
np.allclose(ab, ba)

True

- 의사 역행렬
    - 역행렬은 정사각행렬 중에 행렬식이 0이 아닌 경우에만 구할 수 있습니다. 특정 행렬이 역행렬
이 없을 때에 역행렬을 임의로 계산하는 것을 의사 역행렬입니다. 

In [95]:
a = np.ones((3,3))

In [96]:
np.linalg.det(a)

0.0

In [97]:
np.linalg.pinv(a)

array([[0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111]])

In [98]:
try:
    np.linalg.inv(a)
except Exception as e:
    print(e)

Singular matrix


- 전치행렬
    - 아인슈타인의 합은 선형대수학을 물리학에 응용하면서 좌표계에 관한 공식을 다룰 때 유용한
    표기규칙으로 선형대수를 편리하게 계산할 수 있는 방법입니다.
    - 전치행렬을 처리하려면 먼저 문자열에 두 행렬의 인덱스 정보를 반대로 만듭니다. 

In [99]:
A = np.array([[1,2,3], [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [101]:
np.einsum('ij->ji',A)

array([[1, 4],
       [2, 5],
       [3, 6]])

- 하나의 벡터와 행렬 계산
    - Einsum으로 벡터의 원소를 합산할 경우는 하나의 인덱스를 표시하고 결과는 아무것도 표시하
    지 않습니다. 
    - 벡터는 하나, 행렬은 두 개의 인덱스를 문자로 표시해야합니다. 

In [102]:
AA = np.arange(10)

In [103]:
np.einsum('i->', AA)

45

In [104]:
np.sum(AA)

45

In [105]:
A_ = np.array([[1,1,1],
               [3,2,4],
               [7,5,8]])

In [107]:
np.einsum('ij->',A_)

32

In [108]:
np.sum(A_)

32

In [109]:
np.einsum('ij->ji',A_)

array([[1, 3, 7],
       [1, 2, 5],
       [1, 4, 8]])

In [110]:
np.sum(A_, axis=1)

array([ 3,  9, 20])

In [113]:
np.einsum('ij->j', A_)

array([11,  8, 13])

In [112]:
np.sum(A_, axis=0)

array([11,  8, 13])

- 두 개의 배열 연산
    - 두 개의 1차원 배열을 가지고 곱셈과 닷연산은 동일한 인덱스 문자를 사용합니다

In [114]:
C = np.arange(10)
D = np.arange(5, 15)

In [115]:
np.einsum('i,i->i', C, D)

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [116]:
np.einsum('i,i->', C, D)

510

In [117]:
np.dot(C,D)

510

- 행벡터와 열벡터의 닷(dot)연산
    - 두 개의 벡터를 행벡터와 열벡터의 닷연산으로 계산이 가능합니다. 

In [118]:
np.einsum('i,j->ij', C, D)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  5,   6,   7,   8,   9,  10,  11,  12,  13,  14],
       [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42],
       [ 20,  24,  28,  32,  36,  40,  44,  48,  52,  56],
       [ 25,  30,  35,  40,  45,  50,  55,  60,  65,  70],
       [ 30,  36,  42,  48,  54,  60,  66,  72,  78,  84],
       [ 35,  42,  49,  56,  63,  70,  77,  84,  91,  98],
       [ 40,  48,  56,  64,  72,  80,  88,  96, 104, 112],
       [ 45,  54,  63,  72,  81,  90,  99, 108, 117, 126]])

In [119]:
np.dot(C.reshape(10,1), D.reshape(1,10))

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  5,   6,   7,   8,   9,  10,  11,  12,  13,  14],
       [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42],
       [ 20,  24,  28,  32,  36,  40,  44,  48,  52,  56],
       [ 25,  30,  35,  40,  45,  50,  55,  60,  65,  70],
       [ 30,  36,  42,  48,  54,  60,  66,  72,  78,  84],
       [ 35,  42,  49,  56,  63,  70,  77,  84,  91,  98],
       [ 40,  48,  56,  64,  72,  80,  88,  96, 104, 112],
       [ 45,  54,  63,  72,  81,  90,  99, 108, 117, 126]])

In [120]:
np.outer(C, D)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  5,   6,   7,   8,   9,  10,  11,  12,  13,  14],
       [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42],
       [ 20,  24,  28,  32,  36,  40,  44,  48,  52,  56],
       [ 25,  30,  35,  40,  45,  50,  55,  60,  65,  70],
       [ 30,  36,  42,  48,  54,  60,  66,  72,  78,  84],
       [ 35,  42,  49,  56,  63,  70,  77,  84,  91,  98],
       [ 40,  48,  56,  64,  72,  80,  88,  96, 104, 112],
       [ 45,  54,  63,  72,  81,  90,  99, 108, 117, 126]])

- 행렬 einnum 연산
    - 두 개의 2차원 배열을 인자로 받아서 행렬의 곱셈, 닷연산 을 einsum 함수로 계산합니다. 

In [121]:
E = np.arange(10).reshape(2,5)
F = np.arange(5, 15).reshape(2,5)

In [122]:
np.einsum('ij,ij->ij', E, F)

array([[  0,   6,  14,  24,  36],
       [ 50,  66,  84, 104, 126]])

In [123]:
np.einsum('ij,jk->ik', E, F.T)

array([[ 80, 130],
       [255, 430]])

In [124]:
np.dot(E, F.T)

array([[ 80, 130],
       [255, 430]])