# 선형대수 기본 알아보기 (Chapter 2)

## 스칼라와 벡터 알아보기

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

- Scalar - 0차원
    - 다차원 배열을 숫자 값만 인자로 전달해서 만들 수 있습니다. 
    - 이때는 숫자만 관리하므로 차원이 0이고 shape가 없습니다.

In [3]:
a = np.array(43)
a

array(43)

In [4]:
type(a)

numpy.ndarray

In [5]:
a.ndim

0

In [6]:
a.shape

()

In [7]:
a.dtype

dtype('int32')

In [8]:
a == 43

True

- Vector - 1차원
    - 1차원 리스트를 인자로 전달해서 다차원 배열을 만듭니다.
    - 이 배열의 차원은 1인 벡터가 만들어집니다

In [9]:
v = np.array([43])
v

array([43])

In [10]:
type(v)

numpy.ndarray

In [11]:
v.ndim

1

In [12]:
v.shape

(1,)

- 벡터 생성 함수 1
    - 특정 범위와 간격을 지정해서 배열을 만드는 arange 함수입니다. 
    - 정수와 실수 등으로 지정해서 다차원 배열을 만들 수 있습니다.

In [13]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
v.dtype

dtype('int32')

In [15]:
v1 = np.arange(10.5, 20.5, .5)
v1

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [16]:
v1.dtype

dtype('float64')

In [17]:
v1.size

20

- 벡터 생성 함수 2
    - 특정 범위를 전부 포함해서 총 원소의 개수에 맞춰서 다차원 배열을 만듭니다.
    - 종료점을 포함하지 않을 때는 endpoint를 False 지정합니다. 원소 값들의 차이인 간격은 retstep=True를 지정해 확인합니다.


In [18]:
la = np.linspace(1, 10, 10)
la

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
la.dtype

dtype('float64')

In [20]:
la1 = np.linspace(1, 10, 10, endpoint=False, retstep=True)
la1

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

- 벡터 생성 함수 3
    - 특정 범위의 log 값을 원소로 다차원 배열을 만들 수 있습니다. 
    - 이 logspace 함수의 결과를 확인해봅니다.

In [21]:
lo = np.logspace(0,2,4)
lo

array([  1.        ,   4.64158883,  21.5443469 , 100.        ])

In [22]:
la2 = np.linspace(0,2,4)
la2

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [23]:
for i in la2:
    print(np.power(10,i))

1.0
4.641588833612778
21.544346900318832
100.0


- 벡터 크기
    - 벡터는 크기와 방향을 가집니다. 다차원 배열로 표시할 때 크기에 대해 계산할 수 있습니다. 
    - 벡터의 크기는 각 원소의 제곱한 후에 합산한 것을 제곱근을 처리합니다.
    - 벡터의 크기를 norm이라고 하고 linalg 모듈에 norm 함수를 사용합니다.

In [24]:
v = np.arange(3,5)
v

array([3, 4])

In [25]:
v_p = np.power(v,2)
v_r = np.sqrt(np.sum(v_p))
v_r

5.0

In [26]:
# 벡터의 크기: norm / linalg 모듈 norm 함수
np.hypot(v[0],v[1])
np.linalg.norm(v)

5.0

- 표준 단위 벡터
    - 표준 단위벡터(standard unit vector)는 위치는 원소 중에 하나가 1이고 나머지 원소가 0입니다. 표준 단위벡터의 표기는 e에 첨자를 부여해서 인덱스의 위치에 해당하는 원소만 1로 가집니다.

In [27]:
e1 = np.array([1,0,0])
np.linalg.norm(e1)

1.0

In [28]:
e2 = np.array([0,1,0])
np.linalg.norm(e2)

1.0

In [29]:
e3 = np.array([0,0,1])
np.linalg.norm(e3)

1.0

- 단위 벡터
    - 일반적인 단위벡터를 구할 때는 벡터의 정규화(normalize)인 벡터의 크기를 구하고 이를 벡터의 원소에 나눠서 구합니다.

In [30]:
v_3 = np.array([1,2,3])
v_3_n = np.linalg.norm(v_3)
v_3_n

3.7416573867739413

In [31]:
v_3_u = v_3 / v_3_n
v_3_u

array([0.26726124, 0.53452248, 0.80178373])

In [32]:
np.linalg.norm(v_3_u)

1.0

- 벡터의 상등
    - 벡터의 상등(equality)은 크기와 방향이 같을 경우를 말합니다. 크기는 같지만 방향이 다르면 상등이라고 볼 수 없습니다. 

In [33]:
a = np.arange(3,5)
b = np.arange(3,5)
np.array_equal(a,b)

True

In [34]:
a_1 = np.linalg.norm(a)
b_1 = np.linalg.norm(b)
a_1 == b_1

True

- 벡터의 거리
    - 두 벡터의 거리는 두 벡터 간의 차를 계산한 후에 제곱을 합니다. 이 모든 것을 합산한 후에 제곱근을 처리합니다. 자세히 보면 피타고라스 정리와 동일합니다.

In [35]:
c = np.arange(10,13)
d = np.arange(0,3)
np.sqrt(np.sum(np.square(c-d)))
np.linalg.norm(c-d)

17.320508075688775

### 행렬(Matrix) 알아보기

- 행렬
    - 두 개의 축 즉 차원을 가진 숫자들의 모임을 행렬이라고 합니다.
    - 첫번째 축을 행, 두번째 축을 열입니다. 각 축에는 인덱스가 부여되어 두 인덱스를 쌍으로
    해서 내부의 원소를 읽습니다.
- 행렬 만들기
    - 리스트가 내포된 리스트를 array 함수에 전달해서 2차원 배열인 행렬을 만듭니다.
    - 행렬은 2차원이므로 ndim 이 2입니다. Shape는 2개의 원소를 가진 튜플입니다. 이 튜플의
    첫번째는 원소는 행, 두번재 원소는 열의 개수입니다.

In [36]:
A = np.array([[43],[44]])
A

array([[43],
       [44]])

In [37]:
type(A)

numpy.ndarray

In [38]:
A.dtype

dtype('int32')

In [39]:
A.ndim

2

In [40]:
A.shape

(2, 1)

- 행렬 랭크
    - 행렬의 랭크는 행렬 내부에 벡터들이 서로 조합해서 구성할 수 없는 벡터의 개수를 의미합니다. 즉 선형독립이 아닌 벡터가 있을 때는 랭크가 작아집니다.

In [41]:
c1 = np.array([[1,2,4],[2,4,8],[3,4,5]])

In [43]:
c1[0]*2 - c1[1]

array([0, 0, 0])

In [44]:
np.linalg.det(c1)
np.linalg.matrix_rank(c1)

2

In [45]:
c2 = np.array([[1,3,4],[1,8,5],[2,3,4]])
np.linalg.matrix_rank(c2)

3

In [46]:
np.linalg.det(c2)
np.linalg.matrix_rank(c2.T)

3

- 축 알아보기 1
    - 행렬은 두 개의 축을 가지므로 내부의 원소를 축(axis)위로 계산이 가능합니다

In [47]:
A = np.array([[2,3],[4,5]])
A.sum()

14

In [48]:
A.sum(axis=0)

array([6, 8])

In [49]:
A.sum(axis=1)

array([5, 9])

- 축 알아보기 2
    - 3차원 텐서(배열)도 축에 따른 계산이 가능합니다. 

In [50]:
C = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [51]:
C.ndim

3

In [52]:
C.shape

(2, 2, 2)

In [53]:
C[0]

array([[1, 2],
       [3, 4]])

In [54]:
C[1]

array([[5, 6],
       [7, 8]])

In [55]:
C.sum(axis=0)

array([[ 6,  8],
       [10, 12]])

In [56]:
C.sum(axis=1)

array([[ 4,  6],
       [12, 14]])

In [57]:
C.sum(axis=2)

array([[ 3,  7],
       [11, 15]])

- 확장 및 축소하기
    - 축을 기준으로 배열의 차원을 확대 및 축소를 함수나 메소드로 처리합니다. 

In [58]:
x = np.array([1,2])
x

array([1, 2])

In [59]:
y = np.expand_dims(x, axis=1)
y

array([[1],
       [2]])

In [60]:
z = np.expand_dims(x, axis=0)
z

array([[1, 2]])

In [61]:
x = np.array([[1,4,5],[4,5,6],[7,8,9]])
x

array([[1, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
x.flatten()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [63]:
x.ravel()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

### 행렬(Matrix) 종류 알아보기

- 정사각행렬 (정방행렬)
    - 행과 열의 길이가 같은 행렬을 말한다. 이 행렬의 대각선 원소를 trace로 처리할 수 있다. 

In [64]:
a = np.array([[1,2,3],[4,5,6],[7,8,8]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [65]:
a.shape

(3, 3)

In [66]:
np.trace(a)

14

In [67]:
a.trace()

14

- 대각행렬
    - 정사각행렬일 때 대각선의 원소를 제외한 모든 원소가 0으로 구성할 수 있습니다. 이런 행
    렬을 대각행렬이라 합니다. 이 행렬을 수식으로 표현하면 A＝(aij)(i, j=1, 2, 3…, n) 일 경우에
    만 값이 들어오고 대각선 이외의 원소는 aij=0(i≠j) 모든 0인 행렬입니다

In [68]:
b = np.array([[1,0,0],[0,3,0],[0,0,5]])
b

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [69]:
b.diagonal()

array([1, 3, 5])

In [70]:
np.diagonal(b)

array([1, 3, 5])

- 삼각행렬
    - 정방행렬의 주 대각선의 위의 인덱스의 원소의 값이 전부 0이고 밑의 원소는 값을 가지는
    행렬을 하삼각행렬입니다. 반대인 경우가 상삼각행렬입니다. 

In [71]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [73]:
b = np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
np.triu(b)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

- 대칭행렬
    - 주 대각선 즉 행과 열의 인덱스가 동일한 원소들을 기준으로 아래의 원소와 위의 원소가 동
    일한 값을 가진 행렬을 말합니다. 대칭행렬을 가지고 전치행렬을 만들어도 동일한 형태를
    유지합니다. 

In [75]:
X = np.array([[1,2,3],[2,3,5],[3,5,6]])
X

array([[1, 2, 3],
       [2, 3, 5],
       [3, 5, 6]])

In [76]:
X.T

array([[1, 2, 3],
       [2, 3, 5],
       [3, 5, 6]])

In [77]:
np.array_equal(X, X.T)

True

In [78]:
np.array_equiv(X, X.T)

True

- 치환행렬
    - 단위행렬이나 행렬의 행을 교환해서 재구성하거나 특정 상수를 곱하고 행을 교환시킬 수도
    있는 행렬이 치환행렬입니다. 이런 행렬은 연립방정식의 해를 구할 때 선형대수로 바꾸어
    서 문제를 풀 때 사용합니다

In [79]:
a = np.arange(1, 10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
b = np.eye(3, dtype='int')
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [81]:
np.dot(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
c = np.array([[0,1,0],[1,0,0],[0,0,1]])
np.dot(a,c)

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

- 직교행렬
    - 직교행렬은 자기 자신의 행렬과 전치행렬을 행렬곱으로 계산하면 단위행렬이 나옵니다. 직교
    행렬의 전치행렬은 곧 역행렬입니다.

In [83]:
from scipy.stats import ortho_group

In [84]:
x = ortho_group.rvs(3)
x

array([[-0.69110556,  0.59397005,  0.41179204],
       [ 0.2893366 ,  0.74947657, -0.59545714],
       [ 0.6623122 ,  0.29237723,  0.6898247 ]])

In [85]:
i3 = np.dot(x,x.T)
i3

array([[1.00000000e+00, 6.81805246e-17, 2.00301398e-17],
       [6.81805246e-17, 1.00000000e+00, 1.80187329e-17],
       [2.00301398e-17, 1.80187329e-17, 1.00000000e+00]])

In [86]:
c = np.eye(3)

In [87]:
np.allclose(c, i3)

True

- 전치행렬
    - 전치행렬은 기존의 행과 열을 서로 바꾸는 것입니다. 보통 위 첨자에 T를 사용합니다. 

In [88]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [89]:
a.T

array([[1, 3],
       [2, 4]])

In [90]:
a.transpose()

array([[1, 3],
       [2, 4]])