# 다차원 배열의 검색 (Chapter 3)

### 배열의 일반 검색

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

- 색인검색
    - 다차원 배열의 index는 0부터 시작하며 하나의 원소를 검색할 때 사용합니다.
    - 벡터일때는 스칼라, 행렬일 때는 벡터를 검색합니다.

In [3]:
v = np.array([1,2,3,4,5])

In [4]:
v[0]

1

In [5]:
v[-1]

5

In [6]:
A = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [7]:
A[0]

array([1, 2, 3, 4, 5])

In [8]:
A[-1]

array([ 6,  7,  8,  9, 10])

- 슬라이스 검색
    - 슬라이스검색은 배열의 부분집합을 만듭니다. 리스트는 새로운 사본을 만들지만 다차원 배열은
    원본 데이터를 유지하는 하나의 뷰(view)를 만듭니다. 또한 다차원 배열에서는 슬라이스검색도 축
    에 따른 다양한 차원을 구분해서 부분집합을 만들 수 있습니다.

In [9]:
B = np.arange(9).reshape(3,3)
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
B.shape

(3, 3)

In [11]:
B[0,:]

array([0, 1, 2])

In [12]:
B[0]

array([0, 1, 2])

In [13]:
B[:,0]

array([0, 3, 6])

- 생략기호를 사용한 접근
    - 모든 것을 다 지정하지 않아도 조회하는 방법이 있습니다. 이때는 생략기호인 점 3개를 연달아서 사용합니다. 생략기호를 사용하면 내부적으로 검색할 때 다차원 배열의 모양을 자동으로 인식해서 처리합니다

In [14]:
A = np.arange(1,60,5).reshape(3,4)
A

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [15]:
A[...]

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [16]:
A[:2, ...]

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36]])

In [17]:
A[..., :2]

array([[ 1,  6],
       [21, 26],
       [41, 46]])

### 논리식 검색과 팬시검색

- 논리 검색 1
    - 논리식을 평가한 후에 참인 경우의 원소만을 검색하는 것을 논리 검색이라고 합니다.

In [18]:
L = np.random.randn(7,4)
L

array([[-0.89234981, -1.72579508,  2.23562607,  0.38126898],
       [-0.51311252, -0.2588881 , -0.55150041, -0.46626091],
       [-0.57901435, -0.10913363,  1.1294728 , -0.72563062],
       [-1.81448939, -1.09472178,  0.6858386 ,  0.53385326],
       [-1.69991703,  0.96944747, -1.30040294, -0.40314247],
       [-0.39689945, -1.2476139 , -0.12328315, -0.92915153],
       [-0.65128559, -1.07675507,  1.80355049, -2.51438887]])

In [19]:
L[L<0]

array([-0.89234981, -1.72579508, -0.51311252, -0.2588881 , -0.55150041,
       -0.46626091, -0.57901435, -0.10913363, -0.72563062, -1.81448939,
       -1.09472178, -1.69991703, -1.30040294, -0.40314247, -0.39689945,
       -1.2476139 , -0.12328315, -0.92915153, -0.65128559, -1.07675507,
       -2.51438887])

- 논리 검색 2
    - 논리 검색을 사용해서 논리식의 평가가 참인 경우의 원소를 변경합니다. 

In [20]:
L[L<0] = 999
L

array([[9.99000000e+02, 9.99000000e+02, 2.23562607e+00, 3.81268983e-01],
       [9.99000000e+02, 9.99000000e+02, 9.99000000e+02, 9.99000000e+02],
       [9.99000000e+02, 9.99000000e+02, 1.12947280e+00, 9.99000000e+02],
       [9.99000000e+02, 9.99000000e+02, 6.85838603e-01, 5.33853260e-01],
       [9.99000000e+02, 9.69447472e-01, 9.99000000e+02, 9.99000000e+02],
       [9.99000000e+02, 9.99000000e+02, 9.99000000e+02, 9.99000000e+02],
       [9.99000000e+02, 9.99000000e+02, 1.80355049e+00, 9.99000000e+02]])

In [21]:
LC = L[L==999]
LC

array([999., 999., 999., 999., 999., 999., 999., 999., 999., 999., 999.,
       999., 999., 999., 999., 999., 999., 999., 999., 999., 999.])

- 논리 검색 3
    - 논리 검색에 주의할 점은 and, or, not 연산을 사용하지 못합니다. 대신 logical_and 등의
함수를 사용합니다.

In [22]:
L = np.arange(0,12)
L

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
try:
    L and L
except Exception as e:
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [24]:
np.logical_and(L,L)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [25]:
L[np.logical_and(L,L)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- 팬시 검색 1
    - 다차원 배열의 검색에 배열을 전달해서 여러 개의 원소를 조회합니다. 팬시검색한 결과
는 새로운 다차원 배열입니다.

In [26]:
x = np.arange(1,15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
pos2 = np.array([1,2,2,2])
x[pos2]

array([2, 3, 3, 3])

In [28]:
c = x[pos2]
np.may_share_memory(x,c)

False

In [29]:
y = x[:4]
np.may_share_memory(x,y)

True

- 팬시 검색 2
    - 팬시 검색할 때 주의할 점은 행과 열을 전부 리스트로 전달할 경우는 두 리스트의 쌍으로
구성해서 배열의 원소를 표시합니다. 원하는 결과를 얻으려면 np.ix_ 함수로 처리해야 합
니다.

In [30]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
x[[3,0]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [32]:
x[[1,2],[2,3]]

array([ 6, 11])

In [33]:
a = np.array([[2,3,4,5],[8,9,0,1]])
a

array([[2, 3, 4, 5],
       [8, 9, 0, 1]])

In [34]:
type(np.ix_)

numpy._ArrayFunctionDispatcher

In [35]:
a[np.ix_ ([0,1],[0,1])]

array([[2, 3],
       [8, 9]])

In [36]:
a1 = a[np.ix_([0],[1,3])]
a2 = a[np.ix_([1],[0,2])]

In [37]:
np.concatenate([a1,a2])

array([[3, 5],
       [8, 0]])

- 팬시 검색 혼용
    - 팬시검색을 일반검색, 슬라이스 검색과 혼합해서 처리가 가능합니다. 팬시검색을 혼합한
결과도 새로운 배열을 만듭니다. 

In [38]:
a = np.reshape(np.arange(10), (2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
x[0, [0,1]]

array([0, 1])

In [40]:
x[1, [0,1]]

array([4, 5])

In [41]:
x[[0,1]]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [42]:
x[[0,1],0]

array([0, 4])

In [43]:
a = x[[0,1],0]

In [44]:
np.may_share_memory(x,a)

False

- 팬시검색을 이용한 축소 및 확대
    - 팬시검색은 새로운 배열을 만들어서 검색할 때 다양한 조건을 넣어서 새로운 배열을 만
들 수 있습니다

In [45]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
a = x[1:, 1:]
a

array([[4, 5],
       [7, 8]])

In [47]:
np.may_share_memory(x,a)

True

In [48]:
a = np.reshape(np.arange(10), (2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
c = a[[1,1,1], np.newaxis]
c

array([[[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]]])

In [50]:
c.shape

(3, 1, 5)

### 메소드나 함수로 검색하기


- 메소드로 검색 1
    - 다차원 배열의 메소드인 item, iview를 사용해서 검색이 가능하고 itemset으로 내
부 원소를 갱신할 수 있습니다

In [51]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
x.item(1)

1

In [53]:
x.item(5)

5

In [54]:
x.item(1,2)

5

In [55]:
x.item((2,2))

8

In [56]:
x.itemset(2,20)
x

array([[ 0,  1, 20],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [57]:
x.itemset((1,2),20)
x

array([[ 0,  1, 20],
       [ 3,  4, 20],
       [ 6,  7,  8]])

In [58]:
x.view()

array([[ 0,  1, 20],
       [ 3,  4, 20],
       [ 6,  7,  8]])

- 메소드로 검색 2
    - 다차원 배열의 take 메소드로 검색하고 put 메소드로 내부 원소를 변경할 수 있
습니다. 

In [59]:
b = np.linspace(1,10,10).reshape(2,5)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [60]:
pos1 = [3,4]
b.take(pos1)

array([4., 5.])

In [61]:
pos2 = [[0,1],[3,4]]
b.take(pos2)

array([[1., 2.],
       [4., 5.]])

In [62]:
c = b.copy()
np.may_share_memory(c,b)

False

In [63]:
c.put(pos1,30)
c

array([[ 1.,  2.,  3., 30., 30.],
       [ 6.,  7.,  8.,  9., 10.]])

In [64]:
c.put(pos1, [50, 50])
c

array([[ 1.,  2.,  3., 50., 50.],
       [ 6.,  7.,  8.,  9., 10.]])

- 질의 함수 1
    - 넘파이 함수 choose는 인덱스로 검색합니다. 

In [65]:
# 넘파이 함수 choose는 인덱스로 검색합니다.
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
np.choose(0,x)

array([0, 1, 2])

In [67]:
np.choose([0],x)

array([0, 1, 2])

In [68]:
np.choose(tuple([0,1,2]),x)

array([0, 4, 8])

In [69]:
np.choose(tuple([2,1,0]),x)

array([6, 4, 2])

- 질의 함수 2
    - 넘파이 where는 조건식 판단을 검색에 넣어서 조회가 가능합니다. 이 두 가지를
합친 함수가 select, extract 입니다.

In [70]:
# 넘파이 where는 조건식 판단을 검색에 넣어서 조회가 가능합니다. 이 두 가지를 합친 함수가 select, extract 입니다.
np.where(x>4)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [71]:
x[np.where(x>4)]

array([5, 6, 7, 8])

In [72]:
a = np.select(x>5, x*2)
a

array([12, 14, 16])

In [73]:
np.extract(x>4, x)

array([5, 6, 7, 8])