In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

# 다차원 배열의 구조 변경하기 (Chapter 5)

### 변경 및 결합 주요 함수

- 배열의 형상 변경
    - 1차원 배열을 만들고 내부의 원소 개수가 동일한 형상을 가진 다른 차원의 배열
    로 변경할 수 있습니다. 
    - Reshape 메소드에 형상을 인자로 전달해서 배열의 형상을 변경합니다. 

In [3]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
x1 = x.reshape(2,8)
x1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [5]:
try:
    x2 = x.reshape(4,5)
except Exception as e:
    print(e)

cannot reshape array of size 16 into shape (4,5)


In [6]:
y1 = x.reshape(4,-1)
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

- 배열의 크기 변경
    - 배열의 크기를 resize로 변경해봅니다. Reshape와 차이점은 더 큰 배열로 확장할 수 있습니다.

In [7]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [8]:
np.resize(a,8)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [9]:
np.append(a,a)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [10]:
b = np.arange(4)

In [12]:
b.resize((4,4))
b

array([[0, 1, 2, 3],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
c = np.arange(8)
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
c.resize(4, refcheck=False)
c

array([0, 1, 2, 3])

- 1차원 배열을 2차원 배열로 변경 1
    - Meshgrid 함수를 사용하면 두 개의 배열을 가지고 확장된 두 개의 다른 배열을
만듭니다.

In [15]:
x = np.arange(3)
y = np.arange(4)

In [16]:
x_, y_ = np.meshgrid(x,y)

In [17]:
x_

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [18]:
y_

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [20]:
x_1 = x.reshape(1,-1)
x_1

array([[0, 1, 2]])

In [21]:
np.concatenate([x_1, x_1, x_1, x_1])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [22]:
y_1 = y.reshape(-1,1)
y_1

array([[0],
       [1],
       [2],
       [3]])

In [23]:
np.concatenate([y_1, y_1, y_1, y_1], axis=1)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

- 1차원 배열을 2차원 배열로 변경 2
    - mgrid 함수에 인자로 슬라이스 전달하면 두 개의 배열을 반환합니다. 

In [24]:
np.arange(10,30,10)

array([10, 20])

In [25]:
np.arange(1,5)

array([1, 2, 3, 4])

In [26]:
np.broadcast_arrays(np.arange(10,30,10).reshape(2,1),
                    np.arange(1,5).reshape(1,4))

[array([[10, 10, 10, 10],
        [20, 20, 20, 20]]),
 array([[1, 2, 3, 4],
        [1, 2, 3, 4]])]

In [27]:
a,b = np.mgrid[10:30:10, 1:5]

In [28]:
a

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [29]:
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

- 1차원 배열을 2차원 배열로 변경 3
    - Ogird함수에 인자로 슬라이스 전달하면 2차원 두 개의 배열을 반환합니다. 첫번
째는 열벡터이고 두번째는 행벡터입니다. 이 두개를 브로드캐스탱해서 동일한
형상의 배열을 만들 수 있습니다. 

In [30]:
c,d = np.ogrid[10:30:10, 1:5]

In [31]:
c

array([[10],
       [20]])

In [32]:
d

array([[1, 2, 3, 4]])

In [33]:
e,f = np.broadcast_arrays(c,d)

In [34]:
e

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [35]:
f

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

- 축이 1인 차원을 줄이기
    - 다차원 배열에서 축의 차원이 1인 것을 없애서 차원을 축소할 필요가 있습니다. 
이때 축소하는 함수 squeeze에 배열을 전달해서 사용합니다. 

In [36]:
x = np.array([[0], [1], [2]])
x

array([[0],
       [1],
       [2]])

In [37]:
x.shape

(3, 1)

In [38]:
np.squeeze(x)

array([0, 1, 2])

In [41]:
# np.squeeze(x,axis=0)

In [43]:
# np.squeeze(x,axis=2)

- 내부 원소를 가지고 배열 확대하기
    - 원소를 반복해서 증가하는 repeat 함수, 주어진 배열의 크키를 확대하는 tile 함수 등을 알아봅니다.

In [44]:
a = np.linspace(1,5,5, dtype=np.int32)
a

array([1, 2, 3, 4, 5])

In [46]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [47]:
e = np.arange(4).reshape(2,2)
e

array([[0, 1],
       [2, 3]])

In [48]:
np.tile(e,2)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

- 배열을 결합하기
    - 동일한 형상을 가진 두 개의 배열을 만들고 concatenate 함수로 수직과 수평으로
결합을 할 수 있습니다.


In [49]:
a = np.linspace(1,6,6, dtype=np.int32).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
b = np.linspace(7,13,6, dtype=np.int32).reshape(2,3)
b

array([[ 7,  8,  9],
       [10, 11, 13]])

In [51]:
np.concatenate([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13]])

In [52]:
np.concatenate([a,b],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 13]])

- 배열을 쌓기
    - 두 개의 일차원 배열을 만들고 stack , vstack, hstack 함수로 배열을 수직과 수평으
로 쌓을 수가 있습니다

In [53]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [54]:
np.stack([x,y])

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np.stack([x,y],axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
a = np.vstack([x,y])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
np.vstack([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [58]:
np.stack([x,y], axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [59]:
b = np.hstack([x,y])
b

array([1, 2, 3, 4, 5, 6])

- 배열을 분리하기
    - 선형대수에서 큰 배열을 작은 배열로 분리해서 계산을 합니다. 넘파이 모듈의 다
차원 배열도 하나의 배열을 분리해서 처리할 수 있습니다.

In [60]:
a = np.linspace(1,6,6, dtype=np.int32).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
b = np.vstack([a,a])
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [62]:
x,y = np.split(b,[2])

In [63]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
y

array([[1, 2, 3],
       [4, 5, 6]])

- 배열 쌓기 객체
    - 행과 열을 쌓을 때 r_, c_ 를 사용할 수도 있습니다. 

In [66]:
a = np.arange(6).reshape(2,3)
c = np.random.randn(2,3)

In [67]:
np.r_[a,c]

array([[ 0.        ,  1.        ,  2.        ],
       [ 3.        ,  4.        ,  5.        ],
       [ 2.21057198, -1.0835959 , -0.53069831],
       [ 2.78466296, -1.1104472 ,  0.0590302 ]])

In [68]:
np.c_[a,c]

array([[ 0.        ,  1.        ,  2.        ,  2.21057198, -1.0835959 ,
        -0.53069831],
       [ 3.        ,  4.        ,  5.        ,  2.78466296, -1.1104472 ,
         0.0590302 ]])